cd /D "%~dp0"
REM Video / Audio
echo Setting Video / Audio File Associations...
%~dp0SetUserFTA.exe .ac3 io.mpv.qt
%~dp0SetUserFTA.exe .a52 io.mpv.qt
%~dp0SetUserFTA.exe .eac3 io.mpv.qt
%~dp0SetUserFTA.exe .mlp io.mpv.qt
%~dp0SetUserFTA.exe .dts io.mpv.qt
%~dp0SetUserFTA.exe .dts-hd io.mpv.qt
%~dp0SetUserFTA.exe .dtshd io.mpv.qt
%~dp0SetUserFTA.exe .true-hd io.mpv.qt
%~dp0SetUserFTA.exe .thd io.mpv.qt
%~dp0SetUserFTA.exe .truehd io.mpv.qt
%~dp0SetUserFTA.exe .thd+ac3 io.mpv.qt
%~dp0SetUserFTA.exe .tta io.mpv.qt
%~dp0SetUserFTA.exe .pcm io.mpv.qt
%~dp0SetUserFTA.exe .wav io.mpv.qt
%~dp0SetUserFTA.exe .aiff io.mpv.qt
%~dp0SetUserFTA.exe .aif io.mpv.qt
%~dp0SetUserFTA.exe .aifc io.mpv.qt
%~dp0SetUserFTA.exe .amr io.mpv.qt
%~dp0SetUserFTA.exe .awb io.mpv.qt
%~dp0SetUserFTA.exe .au io.mpv.qt
%~dp0SetUserFTA.exe .snd io.mpv.qt
%~dp0SetUserFTA.exe .lpcm io.mpv.qt
%~dp0SetUserFTA.exe .yuv io.mpv.qt
%~dp0SetUserFTA.exe .y4m io.mpv.qt
%~dp0SetUserFTA.exe .ape io.mpv.qt
%~dp0SetUserFTA.exe .wv io.mpv.qt
%~dp0SetUserFTA.exe .shn io.mpv.qt
%~dp0SetUserFTA.exe .m2ts io.mpv.qt
%~dp0SetUserFTA.exe .m2t io.mpv.qt
%~dp0SetUserFTA.exe .mts io.mpv.qt
%~dp0SetUserFTA.exe .mtv io.mpv.qt
%~dp0SetUserFTA.exe .ts io.mpv.qt
%~dp0SetUserFTA.exe .tsv io.mpv.qt
%~dp0SetUserFTA.exe .tsa io.mpv.qt
%~dp0SetUserFTA.exe .tts io.mpv.qt
%~dp0SetUserFTA.exe .trp io.mpv.qt
%~dp0SetUserFTA.exe .adts io.mpv.qt
%~dp0SetUserFTA.exe .adt io.mpv.qt
%~dp0SetUserFTA.exe .mpa io.mpv.qt
%~dp0SetUserFTA.exe .m1a io.mpv.qt
%~dp0SetUserFTA.exe .m2a io.mpv.qt
%~dp0SetUserFTA.exe .mp1 io.mpv.qt
%~dp0SetUserFTA.exe .mp2 io.mpv.qt
%~dp0SetUserFTA.exe .mp3 io.mpv.qt
%~dp0SetUserFTA.exe .mpeg io.mpv.qt
%~dp0SetUserFTA.exe .mpg io.mpv.qt
%~dp0SetUserFTA.exe .mpe io.mpv.qt
%~dp0SetUserFTA.exe .mpeg2 io.mpv.qt
%~dp0SetUserFTA.exe .m1v io.mpv.qt
%~dp0SetUserFTA.exe .m2v io.mpv.qt
%~dp0SetUserFTA.exe .mp2v io.mpv.qt
%~dp0SetUserFTA.exe .mpv io.mpv.qt
%~dp0SetUserFTA.exe .mpv2 io.mpv.qt
%~dp0SetUserFTA.exe .mod io.mpv.qt
%~dp0SetUserFTA.exe .tod io.mpv.qt
%~dp0SetUserFTA.exe .vob io.mpv.qt
%~dp0SetUserFTA.exe .vro io.mpv.qt
%~dp0SetUserFTA.exe .evob io.mpv.qt
%~dp0SetUserFTA.exe .evo io.mpv.qt
%~dp0SetUserFTA.exe .mpeg4 io.mpv.qt
%~dp0SetUserFTA.exe .m4v io.mpv.qt
%~dp0SetUserFTA.exe .mp4 io.mpv.qt
%~dp0SetUserFTA.exe .mp4v io.mpv.qt
%~dp0SetUserFTA.exe .mpg4 io.mpv.qt
%~dp0SetUserFTA.exe .m4a io.mpv.qt
%~dp0SetUserFTA.exe .aac io.mpv.qt
%~dp0SetUserFTA.exe .h264 io.mpv.qt
%~dp0SetUserFTA.exe .avc io.mpv.qt
%~dp0SetUserFTA.exe .x264 io.mpv.qt
%~dp0SetUserFTA.exe .264 io.mpv.qt
%~dp0SetUserFTA.exe .hevc io.mpv.qt
%~dp0SetUserFTA.exe .h265 io.mpv.qt
%~dp0SetUserFTA.exe .x265 io.mpv.qt
%~dp0SetUserFTA.exe .265 io.mpv.qt
%~dp0SetUserFTA.exe .flac io.mpv.qt
%~dp0SetUserFTA.exe .oga io.mpv.qt
%~dp0SetUserFTA.exe .ogg io.mpv.qt
%~dp0SetUserFTA.exe .opus io.mpv.qt
%~dp0SetUserFTA.exe .spx io.mpv.qt
%~dp0SetUserFTA.exe .ogv io.mpv.qt
%~dp0SetUserFTA.exe .ogm io.mpv.qt
%~dp0SetUserFTA.exe .ogx io.mpv.qt
%~dp0SetUserFTA.exe .mkv io.mpv.qt
%~dp0SetUserFTA.exe .mk3d io.mpv.qt
%~dp0SetUserFTA.exe .mka io.mpv.qt
%~dp0SetUserFTA.exe .webm io.mpv.qt
%~dp0SetUserFTA.exe .weba io.mpv.qt
%~dp0SetUserFTA.exe .avi io.mpv.qt
%~dp0SetUserFTA.exe .vfw io.mpv.qt
%~dp0SetUserFTA.exe .divx io.mpv.qt
%~dp0SetUserFTA.exe .3iv io.mpv.qt
%~dp0SetUserFTA.exe .xvid io.mpv.qt
%~dp0SetUserFTA.exe .nut io.mpv.qt
%~dp0SetUserFTA.exe .flic io.mpv.qt
%~dp0SetUserFTA.exe .fli io.mpv.qt
%~dp0SetUserFTA.exe .flc io.mpv.qt
%~dp0SetUserFTA.exe .nsv io.mpv.qt
%~dp0SetUserFTA.exe .gxf io.mpv.qt
%~dp0SetUserFTA.exe .mxf io.mpv.qt
%~dp0SetUserFTA.exe .wma io.mpv.qt
%~dp0SetUserFTA.exe .wm io.mpv.qt
%~dp0SetUserFTA.exe .wmv io.mpv.qt
%~dp0SetUserFTA.exe .asf io.mpv.qt
%~dp0SetUserFTA.exe .dvr-ms io.mpv.qt
%~dp0SetUserFTA.exe .dvr io.mpv.qt
%~dp0SetUserFTA.exe .wtv io.mpv.qt
%~dp0SetUserFTA.exe .dv io.mpv.qt
%~dp0SetUserFTA.exe .hdv io.mpv.qt
%~dp0SetUserFTA.exe .flv io.mpv.qt
%~dp0SetUserFTA.exe .f4v io.mpv.qt
%~dp0SetUserFTA.exe .f4a io.mpv.qt
%~dp0SetUserFTA.exe .qt io.mpv.qt
%~dp0SetUserFTA.exe .mov io.mpv.qt
%~dp0SetUserFTA.exe .hdmov io.mpv.qt
%~dp0SetUserFTA.exe .rm io.mpv.qt
%~dp0SetUserFTA.exe .rmvb io.mpv.qt
%~dp0SetUserFTA.exe .ra io.mpv.qt
%~dp0SetUserFTA.exe .ram io.mpv.qt
%~dp0SetUserFTA.exe .3ga io.mpv.qt
%~dp0SetUserFTA.exe .3ga2 io.mpv.qt
%~dp0SetUserFTA.exe .3gpp io.mpv.qt
%~dp0SetUserFTA.exe .3gp io.mpv.qt
%~dp0SetUserFTA.exe .3gp2 io.mpv.qt
%~dp0SetUserFTA.exe .3g2 io.mpv.qt
%~dp0SetUserFTA.exe .ay io.mpv.qt
%~dp0SetUserFTA.exe .gbs io.mpv.qt
%~dp0SetUserFTA.exe .gym io.mpv.qt
%~dp0SetUserFTA.exe .hes io.mpv.qt
%~dp0SetUserFTA.exe .kss io.mpv.qt
%~dp0SetUserFTA.exe .nsf io.mpv.qt
%~dp0SetUserFTA.exe .nsfe io.mpv.qt
%~dp0SetUserFTA.exe .sap io.mpv.qt
%~dp0SetUserFTA.exe .spc io.mpv.qt
%~dp0SetUserFTA.exe .vgm io.mpv.qt
%~dp0SetUserFTA.exe .vgz io.mpv.qt
%~dp0SetUserFTA.exe .m3u io.mpv.qt
%~dp0SetUserFTA.exe .m3u8 io.mpv.qt
%~dp0SetUserFTA.exe .pls io.mpv.qt
%~dp0SetUserFTA.exe .cue io.mpv.qt

REM Photos
echo Setting Photo File Associations...
%~dp0SetUserFTA.exe .ase qView.1
%~dp0SetUserFTA.exe .art qView.1
%~dp0SetUserFTA.exe .bmp qView.1
%~dp0SetUserFTA.exe .blp qView.1
%~dp0SetUserFTA.exe .cd5 qView.1
%~dp0SetUserFTA.exe .cit qView.1
%~dp0SetUserFTA.exe .cpt qView.1
%~dp0SetUserFTA.exe .cr2 qView.1
%~dp0SetUserFTA.exe .cut qView.1
%~dp0SetUserFTA.exe .dds qView.1
%~dp0SetUserFTA.exe .dib qView.1
%~dp0SetUserFTA.exe .djvu qView.1
%~dp0SetUserFTA.exe .egt qView.1
%~dp0SetUserFTA.exe .exif qView.1
%~dp0SetUserFTA.exe .gif qView.1
%~dp0SetUserFTA.exe .gpl qView.1
%~dp0SetUserFTA.exe .grf qView.1
%~dp0SetUserFTA.exe .icns qView.1
%~dp0SetUserFTA.exe .ico qView.1
%~dp0SetUserFTA.exe .iff qView.1
%~dp0SetUserFTA.exe .jng qView.1
%~dp0SetUserFTA.exe .jpeg qView.1
%~dp0SetUserFTA.exe .jpg qView.1
%~dp0SetUserFTA.exe .jfif qView.1
%~dp0SetUserFTA.exe .jp2 qView.1
%~dp0SetUserFTA.exe .jps qView.1
%~dp0SetUserFTA.exe .lbm qView.1
%~dp0SetUserFTA.exe .max qView.1
%~dp0SetUserFTA.exe .miff qView.1
%~dp0SetUserFTA.exe .mng qView.1
%~dp0SetUserFTA.exe .msp qView.1
%~dp0SetUserFTA.exe .nef qView.1
%~dp0SetUserFTA.exe .nitf qView.1
%~dp0SetUserFTA.exe .ota qView.1
%~dp0SetUserFTA.exe .pbm qView.1
%~dp0SetUserFTA.exe .pc1 qView.1
%~dp0SetUserFTA.exe .pc2 qView.1
%~dp0SetUserFTA.exe .pc3 qView.1
%~dp0SetUserFTA.exe .pcf qView.1
%~dp0SetUserFTA.exe .pcx qView.1
%~dp0SetUserFTA.exe .pdn qView.1
%~dp0SetUserFTA.exe .pgm qView.1
%~dp0SetUserFTA.exe .PI1 qView.1
%~dp0SetUserFTA.exe .PI2 qView.1
%~dp0SetUserFTA.exe .PI3 qView.1
%~dp0SetUserFTA.exe .pict qView.1
%~dp0SetUserFTA.exe .pct qView.1
%~dp0SetUserFTA.exe .pnm qView.1
%~dp0SetUserFTA.exe .pns qView.1
%~dp0SetUserFTA.exe .ppm qView.1
%~dp0SetUserFTA.exe .psb qView.1
%~dp0SetUserFTA.exe .psd qView.1
%~dp0SetUserFTA.exe .pdd qView.1
%~dp0SetUserFTA.exe .psp qView.1
%~dp0SetUserFTA.exe .px qView.1
%~dp0SetUserFTA.exe .pxm qView.1
%~dp0SetUserFTA.exe .pxr qView.1
%~dp0SetUserFTA.exe .qfx qView.1
%~dp0SetUserFTA.exe .raw qView.1
%~dp0SetUserFTA.exe .rle qView.1
%~dp0SetUserFTA.exe .sct qView.1
%~dp0SetUserFTA.exe .sgi qView.1
%~dp0SetUserFTA.exe .rgb qView.1
%~dp0SetUserFTA.exe .int qView.1
%~dp0SetUserFTA.exe .bw qView.1
%~dp0SetUserFTA.exe .tga qView.1
%~dp0SetUserFTA.exe .tiff qView.1
%~dp0SetUserFTA.exe .tif qView.1
%~dp0SetUserFTA.exe .vtf qView.1
%~dp0SetUserFTA.exe .xbm qView.1
%~dp0SetUserFTA.exe .xpm qView.1
%~dp0SetUserFTA.exe .3dv qView.1
%~dp0SetUserFTA.exe .amf qView.1
%~dp0SetUserFTA.exe .ai qView.1
%~dp0SetUserFTA.exe .awg qView.1
%~dp0SetUserFTA.exe .cgm qView.1
%~dp0SetUserFTA.exe .cdr qView.1
%~dp0SetUserFTA.exe .cmx qView.1
%~dp0SetUserFTA.exe .dxf qView.1
%~dp0SetUserFTA.exe .e2d qView.1
%~dp0SetUserFTA.exe .egt qView.1
%~dp0SetUserFTA.exe .eps qView.1
%~dp0SetUserFTA.exe .fs qView.1
%~dp0SetUserFTA.exe .gbr qView.1
%~dp0SetUserFTA.exe .odg qView.1
%~dp0SetUserFTA.exe .svg qView.1
%~dp0SetUserFTA.exe .stl qView.1
%~dp0SetUserFTA.exe .vrml qView.1
%~dp0SetUserFTA.exe .x3d qView.1
%~dp0SetUserFTA.exe .sxd qView.1
%~dp0SetUserFTA.exe .v2d qView.1
%~dp0SetUserFTA.exe .vnd qView.1
%~dp0SetUserFTA.exe .wmf qView.1
%~dp0SetUserFTA.exe .emf qView.1
%~dp0SetUserFTA.exe .art qView.1
%~dp0SetUserFTA.exe .xar qView.1
%~dp0SetUserFTA.exe .png qView.1
%~dp0SetUserFTA.exe .webp qView.1
%~dp0SetUserFTA.exe .jxr qView.1
%~dp0SetUserFTA.exe .hdp qView.1
%~dp0SetUserFTA.exe .wdp qView.1
%~dp0SetUserFTA.exe .cur qView.1
%~dp0SetUserFTA.exe .ecw qView.1
%~dp0SetUserFTA.exe .iff qView.1
%~dp0SetUserFTA.exe .lbm qView.1
%~dp0SetUserFTA.exe .liff qView.1
%~dp0SetUserFTA.exe .nrrd qView.1
%~dp0SetUserFTA.exe .pam qView.1
%~dp0SetUserFTA.exe .pcx qView.1
%~dp0SetUserFTA.exe .pgf qView.1
%~dp0SetUserFTA.exe .sgi qView.1
%~dp0SetUserFTA.exe .rgb qView.1
%~dp0SetUserFTA.exe .rgba qView.1
%~dp0SetUserFTA.exe .bw qView.1
%~dp0SetUserFTA.exe .int qView.1
%~dp0SetUserFTA.exe .inta qView.1
%~dp0SetUserFTA.exe .sid qView.1
%~dp0SetUserFTA.exe .ras qView.1
%~dp0SetUserFTA.exe .sun qView.1
%~dp0SetUserFTA.exe .tga qView.1
%~dp0SetUserFTA.exe .heic qView.1
%~dp0SetUserFTA.exe .heif qView.1
%~dp0SetUserFTA.exe .ico qView.1

REM Programing
echo Setting Programing File Associations...
%~dp0SetUserFTA.exe .txt Applications\Notepad4.exe
%~dp0SetUserFTA.exe .c Applications\Notepad4.exe
%~dp0SetUserFTA.exe .cpp Applications\Notepad4.exe
%~dp0SetUserFTA.exe .cs Applications\Notepad4.exe
%~dp0SetUserFTA.exe .py Applications\Notepad4.exe
%~dp0SetUserFTA.exe .log Applications\Notepad4.exe
%~dp0SetUserFTA.exe .xml Applications\Notepad4.exe
%~dp0SetUserFTA.exe .md Applications\Notepad4.exe
%~dp0SetUserFTA.exe .json Applications\Notepad4.exe
%~dp0SetUserFTA.exe .sln Applications\Notepad4.exe
%~dp0SetUserFTA.exe .yml Applications\Notepad4.exe
%~dp0SetUserFTA.exe .csproj Applications\Notepad4.exe
%~dp0SetUserFTA.exe .config Applications\Notepad4.exe
%~dp0SetUserFTA.exe .conf Applications\Notepad4.exe
%~dp0SetUserFTA.exe .ini Applications\Notepad4.exe
%~dp0SetUserFTA.exe .inf Applications\Notepad4.exe
%~dp0SetUserFTA.exe .nfo Applications\Notepad4.exe

REM Archive
echo Setting Archive File Associations...
%~dp0SetUserFTA.exe .rar WinRAR
%~dp0SetUserFTA.exe .zip WinRAR
%~dp0SetUserFTA.exe .7z WinRAR
%~dp0SetUserFTA.exe .arj WinRAR
%~dp0SetUserFTA.exe .bz2 WinRAR
%~dp0SetUserFTA.exe .cab WinRAR
%~dp0SetUserFTA.exe .gz WinRAR
%~dp0SetUserFTA.exe .lz WinRAR
%~dp0SetUserFTA.exe .lzh WinRAR
%~dp0SetUserFTA.exe .tar WinRAR
%~dp0SetUserFTA.exe .uue WinRAR
%~dp0SetUserFTA.exe .xz WinRAR
%~dp0SetUserFTA.exe .z WinRAR
%~dp0SetUserFTA.exe .zipx WinRAR
%~dp0SetUserFTA.exe .zst WinRAR
%~dp0SetUserFTA.exe .001 WinRAR
