@echo off
::Movie File Extension Changer (MFEC)

cd %~dp0
echo Setting App as default for
echo VLC Movies
Tools\SetUserFTA.exe .webm VLC.webm 
Tools\SetUserFTA.exe .mkv VLC.mkv 
Tools\SetUserFTA.exe .flv VLC.flv 
Tools\SetUserFTA.exe .vob VLC.vob 
Tools\SetUserFTA.exe .ogv VLC.ogv 
Tools\SetUserFTA.exe .ogg VLC.ogg 
Tools\SetUserFTA.exe .rrc VLC.rrc 
Tools\SetUserFTA.exe .gifv VLC.gifv 
Tools\SetUserFTA.exe .mng VLC.mng 
Tools\SetUserFTA.exe .mov VLC.mov 
Tools\SetUserFTA.exe .avi VLC.avi 
Tools\SetUserFTA.exe .qt VLC.qt 
Tools\SetUserFTA.exe .wmv VLC.wmv 
Tools\SetUserFTA.exe .yuv VLC.yuv 
Tools\SetUserFTA.exe .rm VLC.rm 
Tools\SetUserFTA.exe .asf VLC.asf 
Tools\SetUserFTA.exe .amv VLC.amv 
Tools\SetUserFTA.exe .mp4 VLC.mp4 
Tools\SetUserFTA.exe .m4p VLC.m4p 
Tools\SetUserFTA.exe .m4v VLC.m4v 
Tools\SetUserFTA.exe .mpg VLC.mpg 
Tools\SetUserFTA.exe .mp2 VLC.mp2 
Tools\SetUserFTA.exe .mpeg VLC.mpeg 
Tools\SetUserFTA.exe .mpe VLC.mpe 
Tools\SetUserFTA.exe .mpv VLC.mpv 
Tools\SetUserFTA.exe .m4v VLC.m4v 
Tools\SetUserFTA.exe .svi VLC.svi 
Tools\SetUserFTA.exe .3gp VLC.3gp 
Tools\SetUserFTA.exe .3g2 VLC.3g2 
Tools\SetUserFTA.exe .mxf VLC.mxf 
Tools\SetUserFTA.exe .roq VLC.roq 
Tools\SetUserFTA.exe .nsv VLC.nsv 
Tools\SetUserFTA.exe .flv VLC.flv 
Tools\SetUserFTA.exe .f4v VLC.f4v 
Tools\SetUserFTA.exe .f4p VLC.f4p 
Tools\SetUserFTA.exe .f4a VLC.f4a 
Tools\SetUserFTA.exe .f4b VLC.f4b 
Tools\SetUserFTA.exe .mod VLC.mod 

echo Microsoft Photos
Tools\SetUserFTA.exe .ase AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .art AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .bmp AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .blp AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .cd5 AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .cit AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .cpt AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .cr2 AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .cut AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .dds AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .dib AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .djvu AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .egt AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .exif AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .gif AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .gpl AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .grf AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .icns AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .ico AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .iff AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .jng AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .jpeg AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .jpg AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .jfif AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .jp2 AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .jps AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .lbm AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .max AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .miff AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .mng AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .msp AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .nef AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .nitf AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .ota AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pbm AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pc1 AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pc2 AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pc3 AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pcf AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pcx AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pdn AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pgm AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .PI1 AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .PI2 AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .PI3 AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pict AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pct AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pnm AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pns AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .ppm AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .psb AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .psd AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pdd AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .psp AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .px AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pxm AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pxr AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .qfx AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .raw AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .rle AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .sct AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .sgi AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .rgb AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .int AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .bw AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .tga AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .tiff AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .tif AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .vtf AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .xbm AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .xcf AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .xpm AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .3dv AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .amf AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .ai AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .awg AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .cgm AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .cdr AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .cmx AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .dxf AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .e2d AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .egt AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .eps AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .fs AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .gbr AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .odg AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .svg AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .stl AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .vrml AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .x3d AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .sxd AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .v2d AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .vnd AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .wmf AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .emf AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .art AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .xar AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .png AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .webp AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .jxr AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .hdp AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .wdp AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .cur AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .ecw AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .iff AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .lbm AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .liff AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .nrrd AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pam AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pcx AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .pgf AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .sgi AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .rgb AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .rgba AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .bw AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .int AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .inta AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .sid AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .ras AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .sun AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .tga AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .heic AppX43hnxtbyyps62jhe9sqpdzxn1790zetc
Tools\SetUserFTA.exe .heif AppX43hnxtbyyps62jhe9sqpdzxn1790zetc

echo VLC Music
Tools\SetUserFTA.exe .3gp VLC.3gp 
Tools\SetUserFTA.exe .aa VLC.aa 
Tools\SetUserFTA.exe .aac VLC.aac 
Tools\SetUserFTA.exe .aax VLC.aax 
Tools\SetUserFTA.exe .act VLC.act 
Tools\SetUserFTA.exe .aiff VLC.aiff 
Tools\SetUserFTA.exe .alac VLC.alac 
Tools\SetUserFTA.exe .amr VLC.amr 
Tools\SetUserFTA.exe .ape VLC.ape 
Tools\SetUserFTA.exe .au VLC.au 
Tools\SetUserFTA.exe .awb VLC.awb 
Tools\SetUserFTA.exe .dss VLC.dss 
Tools\SetUserFTA.exe .dvf VLC.dvf 
Tools\SetUserFTA.exe .flac VLC.flac 
Tools\SetUserFTA.exe .gsm VLC.gsm 
Tools\SetUserFTA.exe .iklax VLC.iklax 
Tools\SetUserFTA.exe .ivs VLC.ivs 
Tools\SetUserFTA.exe .m4a VLC.m4a 
Tools\SetUserFTA.exe .m4b VLC.m4b 
Tools\SetUserFTA.exe .m4p VLC.m4p 
Tools\SetUserFTA.exe .mmf VLC.mmf 
Tools\SetUserFTA.exe .mp3 VLC.mp3 
Tools\SetUserFTA.exe .mpc VLC.mpc 
Tools\SetUserFTA.exe .msv VLC.msv 
Tools\SetUserFTA.exe .nmf VLC.nmf 
Tools\SetUserFTA.exe .ogg VLC.ogg 
Tools\SetUserFTA.exe .oga VLC.oga 
Tools\SetUserFTA.exe .mogg VLC.mogg 
Tools\SetUserFTA.exe .opus VLC.opus 
Tools\SetUserFTA.exe .ra VLC.ra 
Tools\SetUserFTA.exe .rm VLC.rm 
Tools\SetUserFTA.exe .raw VLC.raw 
Tools\SetUserFTA.exe .rf64 VLC.rf64 
Tools\SetUserFTA.exe .sln VLC.sln 
Tools\SetUserFTA.exe .tta VLC.tta 
Tools\SetUserFTA.exe .voc VLC.voc 
Tools\SetUserFTA.exe .vox VLC.vox 
Tools\SetUserFTA.exe .wav VLC.wav 
Tools\SetUserFTA.exe .wma VLC.wma 
Tools\SetUserFTA.exe .wv VLC.wv 
Tools\SetUserFTA.exe .webm VLC.webm 
Tools\SetUserFTA.exe .8svx VLC.8svx 
Tools\SetUserFTA.exe .cda VLC.cda

echo WinRAR
Tools\SetUserFTA.exe .rar WinRAR
Tools\SetUserFTA.exe .zip WinRAR
Tools\SetUserFTA.exe .7z WinRAR
Tools\SetUserFTA.exe .arj WinRAR
Tools\SetUserFTA.exe .bz2 WinRAR
Tools\SetUserFTA.exe .cab WinRAR
Tools\SetUserFTA.exe .gz WinRAR
Tools\SetUserFTA.exe .lz WinRAR
Tools\SetUserFTA.exe .lzh WinRAR
Tools\SetUserFTA.exe .tar WinRAR
Tools\SetUserFTA.exe .uue WinRAR
Tools\SetUserFTA.exe .xz WinRAR
Tools\SetUserFTA.exe .z WinRAR
Tools\SetUserFTA.exe .zipx WinRAR
Tools\SetUserFTA.exe .zst WinRAR
Tools\SetUserFTA.exe .001 WinRAR

echo Adobe Acrobat
Tools\SetUserFTA.exe .pdf Acrobat.Document.DC
Tools\SetUserFTA.exe .fdf Acrobat.Document.DC
Tools\SetUserFTA.exe .xfdf Acrobat.Document.DC
Tools\SetUserFTA.exe .pdfxml Acrobat.Document.DC
Tools\SetUserFTA.exe .xdp Acrobat.Document.DC
Tools\SetUserFTA.exe .pdx Acrobat.Document.DC
Tools\SetUserFTA.exe .p7m Acrobat.Document.DC
Tools\SetUserFTA.exe .p7c Acrobat.Document.DC
Tools\SetUserFTA.exe .p7s Acrobat.Document.DC
Tools\SetUserFTA.exe .p7b Acrobat.Document.DC
Tools\SetUserFTA.exe .pfx Acrobat.Document.DC
Tools\SetUserFTA.exe .epub Acrobat.Document.DC
Tools\SetUserFTA.exe .mobi Acrobat.Document.DC
Tools\SetUserFTA.exe .azw Acrobat.Document.DC
Tools\SetUserFTA.exe .azw3 Acrobat.Document.DC
Tools\SetUserFTA.exe .djvu Acrobat.Document.DC
Tools\SetUserFTA.exe .djv Acrobat.Document.DC

echo Firefox
Tools\SetUserFTA.exe .htm FirefoxHTML-308046B0AF4A39CB
Tools\SetUserFTA.exe .html FirefoxHTML-308046B0AF4A39CB
start ms-settings:defaultapps
exit
